prefix: '&6[&aEssentials&bMini&6] &c>> &f'
Back: true
DisableTabComplete: false
JoinBoolean: true
JoinMessage: '&aWelcome &6%Player% &aon this Server!'
LeaveBoolean: true
LeaveMessage: '&6%Player% &ahas left the Server!'
Backpack: false
BackPackSize: 36
SpawnTP: false
SkipNight: false
BedColor: 'BLUE'
WarpGUI: false
IgnoreJoinLeave: false
Invsee:
  Owner: true
HomeTP: true
SendPlayerUpdateMessage: true
StartBalance:
  Amount: 1000.0
  Boolean: false
MoneySign:
  Balance: '&b[§6Balance§b]'
  Buy: '&a[§6Buy§a]'
  Sell: '&a[§6Sell§a]'
  Free: '&a[§6Free§a]'
#MySQL Connection!
MySQL:
  Host: ' '
  User: ' '
  Password: ' '
  Database: ' '
  Port: 3306
  Use: false
# Default Path plugins/EssentialsMini
SQLite:
  Path: 'plugins/EssentialsMini'
  FileName: 'database'
  Use: false
PostgreSQL:
  Url: ' '
  User: ' '
  Password: ' '
  Use: false
MongoDB:
  Host: ' '
  Port: 27017
  Database: ' '
  User: ' '
  Password: ' '
  Boolean: false
  LocalHost: false
OnlineMode: true
Currency:
  Single: '$'
  Multi: '$'
Vanish:
  Message: false
Economy:
  Activate: false
  MaxBalance: 1000000
TeleportInOtherWorld: true
AFK:
  Time: 120
  Boolean: false
  IsAFK: '&7[Player] is now AFK'
  IsNotAFK: '&7[Player] is no longer AFK'
NotAllowCommand: '&cNope'
AutoDownload: false
checkForUpdates: false
ColoredChat: true
ColoredSigns: true
PlayerShop: true
PlayerEvents: false
TeleportDelay: 3
Bank: true
msg:
  notificationTo: "&cme &r→ &a %TARGET% &f» %MESSAGE%"
  notificationFrom: "&a%TARGET% &r→ &cme  &f» %MESSAGE%"
  consoleName: "Console"
spawnTpIgnoreWorlds:
  - world_nether
  - world_the_end
maintenance:
  enabled: false
  kickMessage: '%Prefix%&cThis server is currently in maintenance mode!'
  motd: "%PREFIX%&c&l»This server is currently in maintenance mode!&r&cPlease try again later!«"
  list:
    added: '%Prefix%&6%Player% &cadded %Target% to the maintenance list!'
    removed: '%Prefix%&6%Player% &cremoved %Target% from the maintenance list!'
    notInList: '%Prefix%&c%Player% is not in the maintenance list!'
  joinMessage: '%Prefix%&6%Player% &cjoined the server in maintenance mode!'
  tabList:
    header: '&c&l»This server is currently in maintenance mode!«'
    footer: '&c&l»This server is currently in maintenance mode!«'
  floodgateBypass: false
playerPingServerMessage: false
globalMute: false
globalMuteMessage:
  enable: '&cGlobal Mute is enabled! You can not send messages!'
  disable: '&aGlobal Mute is disabled! You can send messages again!'
  chat: '&cGlobal Mute is enabled! You can not send messages!'
  bypass: '&6[%Player%] &f %Message%'

mail:
  enable: true
  maxMessages: 100
  message:
    send: '&aYou have sent a message to %Player%!'
    receive: '&aYou have received a message from %Player%!'
    noMessages: '&cYou have no messages!'
    delete: '&aYou have deleted the message from %Player%!'
    notFound: '&cMessage not found!'
    list: '&aYou have &6%Count% &amessages!'
    sender: '&6[Mail] &f%Sender% &7» &f%Message%'

geyser-support: false
debug: false
